const refs = {
  teamList: document.querySelector('.team-list'),
  teamBtn: document.querySelector('.page-footer__action-btn'),
  lightboxBtn: document.querySelector('.lightbox-button'),
  lightboxContainer: document.querySelector('.js-lightbox'),
  movieList: document.querySelector('.main__section-list'),
  iconCloseBtn: document.querySelectorAll('.close-icon-container'),
  loginModal: document.querySelector('.login-page'),
  closeBtn: document.querySelector('.close-icon-container'),
  loginBtn: document.querySelector('#login'),
  regForm: document.querySelector('.register-form'),
  logForm: document.querySelector('.login-form'),
  createLink: document.querySelector('.create-message a'),
  loginLink: document.querySelector('.login-message a'),
  header: document.getElementById('page-header'),
  navMenu: document.getElementById('page-nav'),
  navLinks: document.querySelectorAll('.link-nav'),
  checkBox: document.querySelector('#theme-switch-toggle'),
  serchForm: document.querySelector('.search-form-js'),
  searchFormInput: document.querySelector('.search-form__input'),
  nextBtn: document.querySelector('.next-btn-js'),
   spinner: document.querySelector('.spinner'),
};

export default refs;
